version: '3.3'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    restart: always

  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 80:80
    command: mvn -Pprod clean spring-boot:run
    depends_on:
      - mongodb
    restart: always
