version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: always

  app:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - mongodb
    restart: always
